---
title: "MLBrunscoring_league"
author: "Martin Monkman"
date: "2019-02-18"
output: html_document
---

#### 

Baseball has characteristics that create an illusion that it has an immutable nature, that the game played today is the same is it was a hundred (or more) years ago. And while it is true there are some elements that have not changed, such as the 90 feet between the bases and three-strikes-and-you're-out, other elements have been constantly shifting. 

One such element in Major League Baseball (MLB) that has fluctuated over time is the number of runs scored per game by each team. And those changes have, for a variety of reasons, been different in the National League (NL) and the American League (AL).

This visualization tool provides a way to explore those changes over time.

On the "team plot" tab, the visualization and accompanying data table show how each of the 30 Major League Baseball teams has performed relative to the shifting league averages, both in terms of the number of runs they have scored, and how many runs they have allowed.
