---
title: "Run scoring trends - references"
author: "Martin Monkman"
date: "2019-02-18"
output: html_document
---

### Major League Baseball run scoring trends


#### bayesball.blogspot.com

Earlier versions of the analysis of run scoring trends in Major League Baseball can be found on my blog [bayesball.blogspot.com](bayesball.blogspot.com).  In reverse order of publication, they are:

* ["Updated Shiny app"](http://bayesball.blogspot.com/2017/03/updated-shiny-app.html), 2017-03-26

* ["Adding a subtitle to ggplot2"](http://bayesball.blogspot.com/2016/03/adding-subtitle-to-ggplot2.html), 2016-03-14

* ["Run scoring trends: using Shiny to create dynamic charts and tables in R: Or, retracing my steps"](http://bayesball.blogspot.com/2015/01/run-scoring-trends-using-shiny-to.html), 2015-01-06

* ["Major League Baseball run scoring trends with R's Lahman package"](http://bayesball.blogspot.ca/2013/06/major-league-baseball-run-scoring.html), 2014-06-04

* ["MLB runs allowed by team; Or, How good were the Maddux/Glavine-era Braves?"](http://bayesball.blogspot.ca/2013/02/mlb-runs-allowed-by-team.html), 2014-02-24

* ["Run production, one team at a time"](http://bayesball.blogspot.ca/2013/02/run-production-one-team-at-time.html), 2013-02-17

* ["Comparing individual team run production; Or, The 2010 Mariners: How Bad Were They?"](http://bayesball.blogspot.ca/2013/02/comparing-individual-team-run-production.html), 2013-02-02

* ["Trends in run scoring - comparing the leagues"](http://bayesball.blogspot.ca/2012/08/trends-in-run-scoring-comparing-leagues.html), 2012-08-10

* ["Trends in run scoring, NL edition (more R)"](http://bayesball.blogspot.ca/2012/07/trends-in-run-scoring-nl-edition-more-r.html), 2012-07-17

* ["Trends in AL run scoring (using R)"](http://bayesball.blogspot.ca/2012/07/trends-in-al-run-scoring-using-r.html), 2012-07-14



*-30-*
